local E, C = unpack(Tukui or ElvUI or AsphyxiaUI or DuffedUI)
local font, fontsize, fontflag, normtex
if ElvUI then
	font, fontsize, fontflag = E["media"].normFont, 12, "OUTLINE"
	normtex = E["media"].normTex
else
	font, fontsize, fontflag = C["media"].pixelfont, 12, "MONOCHROMEOUTLINE"
	normtex = C["media"].normTex
end

local TukuiPetBattleHUD_Pet1 = CreateFrame("Frame", "TukuiPetBattleHUD_Pet1", UIParent)
TukuiPetBattleHUD_Pet1:SetMovable(true)
TukuiPetBattleHUD_Pet1:EnableMouse(true)
TukuiPetBattleHUD_Pet1:RegisterForDrag("LeftButton")
TukuiPetBattleHUD_Pet1:SetScript("OnDragStart", function(self) self:StartMoving() end)
TukuiPetBattleHUD_Pet1:SetScript("OnDragStop", function(self) self:StopMovingOrSizing()  end)
TukuiPetBattleHUD_Pet1:Size(250, 60)
TukuiPetBattleHUD_Pet1:CreateBackdrop("Transparent")
TukuiPetBattleHUD_Pet1:Point("CENTER", UIParent, "CENTER", 0, 200)
TukuiPetBattleHUD_Pet1NameText = TukuiPetBattleHUD_Pet1:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet1NameText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet1NameText:SetPoint("TOPLEFT", TukuiPetBattleHUD_Pet1, "TOPLEFT", 56, -5)

local TukuiPetBattleHUD_Pet1IconBackdrop = CreateFrame("Frame", "TukuiPetBattleHUD_Pet1IconBackdrop", TukuiPetBattleHUD_Pet1)
TukuiPetBattleHUD_Pet1IconBackdrop:SetPoint("LEFT", TukuiPetBattleHUD_Pet1, "LEFT", 10, 0)
TukuiPetBattleHUD_Pet1IconBackdrop:CreateBackdrop()
TukuiPetBattleHUD_Pet1IconBackdrop:Size(40)
TukuiPetBattleHUD_Pet1IconBackdropText = TukuiPetBattleHUD_Pet1IconBackdrop:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet1IconBackdropText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet1IconBackdropText:SetPoint("BOTTOMRIGHT", TukuiPetBattleHUD_Pet1IconBackdrop.backdrop, "BOTTOMRIGHT", 0, 2)

local TukuiPetBattleHUD_Pet1IconBackdropTexture = TukuiPetBattleHUD_Pet1IconBackdrop:CreateTexture("TukuiPetBattleHUD_Pet1IconBackdropTexture", "OVERLAY")
TukuiPetBattleHUD_Pet1IconBackdropTexture:SetTexCoord(0.08, 0.92, 0.08, 0.92)
TukuiPetBattleHUD_Pet1IconBackdropTexture:SetInside(TukuiPetBattleHUD_Pet1IconBackdrop.backdrop)

local TukuiPetBattleHUD_Pet1Health = CreateFrame('StatusBar', "TukuiPetBattleHUD_Pet1Health", TukuiPetBattleHUD_Pet1)
TukuiPetBattleHUD_Pet1Health:SetPoint("LEFT", TukuiPetBattleHUD_Pet1IconBackdrop.backdrop, "RIGHT", 4, 0)
TukuiPetBattleHUD_Pet1Health:Size(150, 10)
TukuiPetBattleHUD_Pet1Health:SetStatusBarTexture(normtex)
TukuiPetBattleHUD_Pet1Health:SetStatusBarColor(0.11,0.66,0.11)
TukuiPetBattleHUD_Pet1Health:SetFrameLevel(TukuiPetBattleHUD_Pet1:GetFrameLevel() + 2)
TukuiPetBattleHUD_Pet1Health:CreateBackdrop()
TukuiPetBattleHUD_Pet1HealthText = TukuiPetBattleHUD_Pet1Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet1HealthText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet1HealthText:SetPoint("CENTER", TukuiPetBattleHUD_Pet1Health.backdrop, "CENTER", 0, 0)
TukuiPetBattleHUD_Pet1AtkPowerIcon = TukuiPetBattleHUD_Pet1:CreateTexture("TukuiPetBattleHUD_Pet1AtkPowerIcon", "OVERLAY")
TukuiPetBattleHUD_Pet1AtkPowerIcon:SetTexture("Interface\\AddOns\\TukuiPetBattleHUD\\AtkPower")
TukuiPetBattleHUD_Pet1AtkPowerIcon:Size(26)
TukuiPetBattleHUD_Pet1AtkPowerIcon:SetPoint("TOPLEFT", TukuiPetBattleHUD_Pet1Health.backdrop, "RIGHT", 2, 8)
TukuiPetBattleHUD_Pet1AtkPowerIconText = TukuiPetBattleHUD_Pet1Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet1AtkPowerIconText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet1AtkPowerIconText:SetPoint("LEFT", TukuiPetBattleHUD_Pet1Health.backdrop, "RIGHT", 20, 2)
TukuiPetBattleHUD_Pet1AtkSpeedIcon = TukuiPetBattleHUD_Pet1:CreateTexture("TukuiPetBattleHUD_Pet1AtkSpeedIcon", "OVERLAY")
TukuiPetBattleHUD_Pet1AtkSpeedIcon:SetTexture("Interface\\AddOns\\TukuiPetBattleHUD\\AtkSpeed")
TukuiPetBattleHUD_Pet1AtkSpeedIcon:Size(26)
TukuiPetBattleHUD_Pet1AtkSpeedIcon:SetPoint("TOPLEFT", TukuiPetBattleHUD_Pet1Health.backdrop, "RIGHT", 2, 4)

local TukuiPetBattleHUD_Pet1Experience = CreateFrame('StatusBar', "TukuiPetBattleHUD_Pet1Experience", TukuiPetBattleHUD_Pet1)
TukuiPetBattleHUD_Pet1Experience:SetPoint("TOP", TukuiPetBattleHUD_Pet1Health, "BOTTOM", 0, -5)
TukuiPetBattleHUD_Pet1Experience:Size(150, 10)
TukuiPetBattleHUD_Pet1Experience:SetStatusBarTexture(normtex)
TukuiPetBattleHUD_Pet1Experience:SetStatusBarColor(0.6,0,0.86)
TukuiPetBattleHUD_Pet1Experience:SetFrameLevel(TukuiPetBattleHUD_Pet1:GetFrameLevel() + 2)
TukuiPetBattleHUD_Pet1Experience:CreateBackdrop()
TukuiPetBattleHUD_Pet1ExperienceText = TukuiPetBattleHUD_Pet1Experience:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet1ExperienceText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet1ExperienceText:SetPoint("CENTER", TukuiPetBattleHUD_Pet1Experience.backdrop, "CENTER", 0, 0)
TukuiPetBattleHUD_Pet1AtkSpeedIconText = TukuiPetBattleHUD_Pet1Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet1AtkSpeedIconText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet1AtkSpeedIconText:SetPoint("LEFT", TukuiPetBattleHUD_Pet1Experience.backdrop, "RIGHT", 20, 0)

local TukuiPetBattleHUD_Pet2 = CreateFrame("Frame", "TukuiPetBattleHUD_Pet2", TukuiPetBattleHUD_Pet1)
TukuiPetBattleHUD_Pet2:Size(250, 60)
TukuiPetBattleHUD_Pet2:CreateBackdrop("Transparent")
TukuiPetBattleHUD_Pet2:Point("TOP", TukuiPetBattleHUD_Pet1, "BOTTOM", 0, -6)
TukuiPetBattleHUD_Pet2NameText = TukuiPetBattleHUD_Pet2:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet2NameText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet2NameText:SetPoint("TOPLEFT", TukuiPetBattleHUD_Pet2, "TOPLEFT", 56, -5)

local TukuiPetBattleHUD_Pet2IconBackdrop = CreateFrame("Frame", "TukuiPetBattleHUD_Pet2IconBackdrop", TukuiPetBattleHUD_Pet2)
TukuiPetBattleHUD_Pet2IconBackdrop:SetPoint("LEFT", TukuiPetBattleHUD_Pet2, "LEFT", 10, 0)
TukuiPetBattleHUD_Pet2IconBackdrop:CreateBackdrop()
TukuiPetBattleHUD_Pet2IconBackdrop:Size(40)
TukuiPetBattleHUD_Pet2IconBackdropText = TukuiPetBattleHUD_Pet2IconBackdrop:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet2IconBackdropText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet2IconBackdropText:SetPoint("BOTTOMRIGHT", TukuiPetBattleHUD_Pet2IconBackdrop.backdrop, "BOTTOMRIGHT", 0, 2)

local TukuiPetBattleHUD_Pet2IconBackdropTexture = TukuiPetBattleHUD_Pet2IconBackdrop:CreateTexture("TukuiPetBattleHUD_Pet2IconBackdropTexture", "OVERLAY")
TukuiPetBattleHUD_Pet2IconBackdropTexture:SetTexCoord(0.08, 0.92, 0.08, 0.92)
TukuiPetBattleHUD_Pet2IconBackdropTexture:SetInside(TukuiPetBattleHUD_Pet2IconBackdrop.backdrop)

local TukuiPetBattleHUD_Pet2Health = CreateFrame('StatusBar', "TukuiPetBattleHUD_Pet2Health", TukuiPetBattleHUD_Pet2)
TukuiPetBattleHUD_Pet2Health:SetPoint("LEFT", TukuiPetBattleHUD_Pet2IconBackdrop.backdrop, "RIGHT", 4, 0)
TukuiPetBattleHUD_Pet2Health:Size(150, 10)
TukuiPetBattleHUD_Pet2Health:SetStatusBarTexture(normtex)
TukuiPetBattleHUD_Pet2Health:SetStatusBarColor(0.11,0.66,0.11)
TukuiPetBattleHUD_Pet2Health:SetFrameLevel(TukuiPetBattleHUD_Pet2:GetFrameLevel() + 2)
TukuiPetBattleHUD_Pet2Health:CreateBackdrop()
TukuiPetBattleHUD_Pet2HealthText = TukuiPetBattleHUD_Pet2Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet2HealthText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet2HealthText:SetPoint("CENTER", TukuiPetBattleHUD_Pet2Health, "CENTER", 0, 1)
TukuiPetBattleHUD_Pet2AtkPowerIcon = TukuiPetBattleHUD_Pet2:CreateTexture("TukuiPetBattleHUD_Pet2AtkPowerIcon", "OVERLAY")
TukuiPetBattleHUD_Pet2AtkPowerIcon:SetTexture("Interface\\AddOns\\TukuiPetBattleHUD\\AtkPower")
TukuiPetBattleHUD_Pet2AtkPowerIcon:Size(26)
TukuiPetBattleHUD_Pet2AtkPowerIcon:SetPoint("TOPLEFT", TukuiPetBattleHUD_Pet2Health.backdrop, "RIGHT", 4, 8)
TukuiPetBattleHUD_Pet2AtkSpeedIcon = TukuiPetBattleHUD_Pet2:CreateTexture("TukuiPetBattleHUD_Pet2AtkSpeedIcon", "OVERLAY")
TukuiPetBattleHUD_Pet2AtkSpeedIcon:SetTexture("Interface\\AddOns\\TukuiPetBattleHUD\\AtkSpeed")
TukuiPetBattleHUD_Pet2AtkSpeedIcon:Size(26)
TukuiPetBattleHUD_Pet2AtkSpeedIcon:SetPoint("TOPLEFT", TukuiPetBattleHUD_Pet2Health.backdrop, "RIGHT", 4, 4)
TukuiPetBattleHUD_Pet2AtkPowerIconText = TukuiPetBattleHUD_Pet2Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet2AtkPowerIconText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet2AtkPowerIconText:SetPoint("LEFT", TukuiPetBattleHUD_Pet2Health.backdrop, "RIGHT", 20, 2)

local TukuiPetBattleHUD_Pet2Experience = CreateFrame('StatusBar', "TukuiPetBattleHUD_Pet2Experience", TukuiPetBattleHUD_Pet2)
TukuiPetBattleHUD_Pet2Experience:SetPoint("TOP", TukuiPetBattleHUD_Pet2Health, "BOTTOM", 0, -5)
TukuiPetBattleHUD_Pet2Experience:Size(150, 10)
TukuiPetBattleHUD_Pet2Experience:SetStatusBarTexture(normtex)
TukuiPetBattleHUD_Pet2Experience:SetStatusBarColor(0.6,0,0.86)
TukuiPetBattleHUD_Pet2Experience:SetFrameLevel(TukuiPetBattleHUD_Pet2:GetFrameLevel() + 2)
TukuiPetBattleHUD_Pet2Experience:CreateBackdrop()
TukuiPetBattleHUD_Pet2ExperienceText = TukuiPetBattleHUD_Pet2Experience:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet2ExperienceText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet2ExperienceText:SetPoint("CENTER", TukuiPetBattleHUD_Pet2Experience.backdrop, "CENTER", 0, 1)
TukuiPetBattleHUD_Pet2AtkSpeedIconText = TukuiPetBattleHUD_Pet2Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet2AtkSpeedIconText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet2AtkSpeedIconText:SetPoint("LEFT", TukuiPetBattleHUD_Pet2Experience.backdrop, "RIGHT", 20, 0)

local TukuiPetBattleHUD_Pet3 = CreateFrame("Frame", "TukuiPetBattleHUD_Pet3", TukuiPetBattleHUD_Pet2)
TukuiPetBattleHUD_Pet3:Size(250, 60)
TukuiPetBattleHUD_Pet3:CreateBackdrop("Transparent")
TukuiPetBattleHUD_Pet3:Point("TOP", TukuiPetBattleHUD_Pet2, "BOTTOM", 0, -6)
TukuiPetBattleHUD_Pet3NameText = TukuiPetBattleHUD_Pet3:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet3NameText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet3NameText:SetPoint("TOPLEFT", TukuiPetBattleHUD_Pet3, "TOPLEFT", 56, -5)

local TukuiPetBattleHUD_Pet3IconBackdrop = CreateFrame("Frame", "TukuiPetBattleHUD_Pet3IconBackdrop", TukuiPetBattleHUD_Pet3)
TukuiPetBattleHUD_Pet3IconBackdrop:SetPoint("LEFT", TukuiPetBattleHUD_Pet3, "LEFT", 10, 0)
TukuiPetBattleHUD_Pet3IconBackdrop:CreateBackdrop()
TukuiPetBattleHUD_Pet3IconBackdrop:Size(40)
TukuiPetBattleHUD_Pet3IconBackdropText = TukuiPetBattleHUD_Pet3IconBackdrop:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet3IconBackdropText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet3IconBackdropText:SetPoint("BOTTOMRIGHT", TukuiPetBattleHUD_Pet3IconBackdrop.backdrop, "BOTTOMRIGHT", 0, 2)

local TukuiPetBattleHUD_Pet3IconBackdropTexture = TukuiPetBattleHUD_Pet3IconBackdrop:CreateTexture("TukuiPetBattleHUD_Pet3IconBackdropTexture", "OVERLAY")
TukuiPetBattleHUD_Pet3IconBackdropTexture:SetTexCoord(0.08, 0.92, 0.08, 0.92)
TukuiPetBattleHUD_Pet3IconBackdropTexture:SetInside(TukuiPetBattleHUD_Pet3IconBackdrop.backdrop)

local TukuiPetBattleHUD_Pet3Health = CreateFrame('StatusBar', "TukuiPetBattleHUD_Pet3Health", TukuiPetBattleHUD_Pet3)
TukuiPetBattleHUD_Pet3Health:SetPoint("LEFT", TukuiPetBattleHUD_Pet3IconBackdrop.backdrop, "RIGHT", 4, 0)
TukuiPetBattleHUD_Pet3Health:Size(150, 10)
TukuiPetBattleHUD_Pet3Health:SetStatusBarTexture(normtex)
TukuiPetBattleHUD_Pet3Health:SetStatusBarColor(0.11,0.66,0.11)
TukuiPetBattleHUD_Pet3Health:SetFrameLevel(TukuiPetBattleHUD_Pet3:GetFrameLevel() + 2)
TukuiPetBattleHUD_Pet3Health:CreateBackdrop()
TukuiPetBattleHUD_Pet3HealthText = TukuiPetBattleHUD_Pet3Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet3HealthText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet3HealthText:SetPoint("CENTER", TukuiPetBattleHUD_Pet3Health, "CENTER", 0, 1)
TukuiPetBattleHUD_Pet3AtkPowerIcon = TukuiPetBattleHUD_Pet3:CreateTexture("TukuiPetBattleHUD_Pet3AtkPowerIcon", "OVERLAY")
TukuiPetBattleHUD_Pet3AtkPowerIcon:SetTexture("Interface\\AddOns\\TukuiPetBattleHUD\\AtkPower")
TukuiPetBattleHUD_Pet3AtkPowerIcon:Size(26)
TukuiPetBattleHUD_Pet3AtkPowerIcon:SetPoint("TOPLEFT", TukuiPetBattleHUD_Pet3Health.backdrop, "RIGHT", 4, 8)
TukuiPetBattleHUD_Pet3AtkSpeedIcon = TukuiPetBattleHUD_Pet3:CreateTexture("TukuiPetBattleHUD_Pet3AtkSpeedIcon", "OVERLAY")
TukuiPetBattleHUD_Pet3AtkSpeedIcon:SetTexture("Interface\\AddOns\\TukuiPetBattleHUD\\AtkSpeed")
TukuiPetBattleHUD_Pet3AtkSpeedIcon:Size(26)
TukuiPetBattleHUD_Pet3AtkSpeedIcon:SetPoint("TOPLEFT", TukuiPetBattleHUD_Pet3Health.backdrop, "RIGHT", 4, 4)
TukuiPetBattleHUD_Pet3AtkPowerIconText = TukuiPetBattleHUD_Pet3Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet3AtkPowerIconText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet3AtkPowerIconText:SetPoint("LEFT", TukuiPetBattleHUD_Pet3Health.backdrop, "RIGHT", 20, 2)

local TukuiPetBattleHUD_Pet3Experience = CreateFrame('StatusBar', "TukuiPetBattleHUD_Pet3Experience", TukuiPetBattleHUD_Pet3)
TukuiPetBattleHUD_Pet3Experience:SetPoint("TOP", TukuiPetBattleHUD_Pet3Health, "BOTTOM", 0, -5)
TukuiPetBattleHUD_Pet3Experience:Size(150, 10)
TukuiPetBattleHUD_Pet3Experience:SetStatusBarTexture(normtex)
TukuiPetBattleHUD_Pet3Experience:SetStatusBarColor(0.6,0,0.86)
TukuiPetBattleHUD_Pet3Experience:SetFrameLevel(TukuiPetBattleHUD_Pet3:GetFrameLevel() + 2)
TukuiPetBattleHUD_Pet3Experience:CreateBackdrop()
TukuiPetBattleHUD_Pet3ExperienceText = TukuiPetBattleHUD_Pet3Experience:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet3ExperienceText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet3ExperienceText:SetPoint("CENTER", TukuiPetBattleHUD_Pet3Experience.backdrop, "CENTER", 0, 1)
TukuiPetBattleHUD_Pet3AtkSpeedIconText = TukuiPetBattleHUD_Pet3Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_Pet3AtkSpeedIconText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_Pet3AtkSpeedIconText:SetPoint("LEFT", TukuiPetBattleHUD_Pet3Experience.backdrop, "RIGHT", 20, 0)

--- Enemy Frames

local TukuiPetBattleHUD_EnemyPet1 = CreateFrame("Frame", "TukuiPetBattleHUD_EnemyPet1", UIParent)
TukuiPetBattleHUD_EnemyPet1:Hide()
TukuiPetBattleHUD_EnemyPet1:SetMovable(true)
TukuiPetBattleHUD_EnemyPet1:EnableMouse(true)
TukuiPetBattleHUD_EnemyPet1:RegisterForDrag("LeftButton")
TukuiPetBattleHUD_EnemyPet1:SetScript("OnDragStart", function(self) self:StartMoving() end)
TukuiPetBattleHUD_EnemyPet1:SetScript("OnDragStop", function(self) self:StopMovingOrSizing()  end)
TukuiPetBattleHUD_EnemyPet1:Size(250, 60)
TukuiPetBattleHUD_EnemyPet1:CreateBackdrop("Transparent")
TukuiPetBattleHUD_EnemyPet1:Point("CENTER", UIParent, "CENTER", 0, 200)
TukuiPetBattleHUD_EnemyPet1NameText = TukuiPetBattleHUD_EnemyPet1:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet1NameText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet1NameText:SetPoint("TOPRIGHT", TukuiPetBattleHUD_EnemyPet1, "TOPRIGHT", -56, -5)

local TukuiPetBattleHUD_EnemyPet1IconBackdrop = CreateFrame("Frame", "TukuiPetBattleHUD_EnemyPet1IconBackdrop", TukuiPetBattleHUD_EnemyPet1)
TukuiPetBattleHUD_EnemyPet1IconBackdrop:SetPoint("RIGHT", TukuiPetBattleHUD_EnemyPet1, "RIGHT", -10, 0)
TukuiPetBattleHUD_EnemyPet1IconBackdrop:CreateBackdrop()
TukuiPetBattleHUD_EnemyPet1IconBackdrop:Size(40)
TukuiPetBattleHUD_EnemyPet1IconBackdropText = TukuiPetBattleHUD_EnemyPet1IconBackdrop:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet1IconBackdropText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet1IconBackdropText:SetPoint("BOTTOMLEFT", TukuiPetBattleHUD_EnemyPet1IconBackdrop.backdrop, "BOTTOMLEFT", 4, 2)

local TukuiPetBattleHUD_EnemyPet1IconBackdropTexture = TukuiPetBattleHUD_EnemyPet1IconBackdrop:CreateTexture("TukuiPetBattleHUD_EnemyPet1IconBackdropTexture", "OVERLAY")
TukuiPetBattleHUD_EnemyPet1IconBackdropTexture:SetTexCoord(0.08, 0.92, 0.08, 0.92)
TukuiPetBattleHUD_EnemyPet1IconBackdropTexture:SetInside(TukuiPetBattleHUD_EnemyPet1IconBackdrop.backdrop)

local TukuiPetBattleHUD_EnemyPet1Health = CreateFrame('StatusBar', "TukuiPetBattleHUD_EnemyPet1Health", TukuiPetBattleHUD_EnemyPet1)
TukuiPetBattleHUD_EnemyPet1Health:SetPoint("RIGHT", TukuiPetBattleHUD_EnemyPet1IconBackdrop.backdrop, "LEFT", -4, 0)
TukuiPetBattleHUD_EnemyPet1Health:Size(150, 10)
TukuiPetBattleHUD_EnemyPet1Health:SetStatusBarTexture(normtex)
TukuiPetBattleHUD_EnemyPet1Health:SetStatusBarColor(0.11,0.66,0.11)
TukuiPetBattleHUD_EnemyPet1Health:SetFrameLevel(TukuiPetBattleHUD_EnemyPet1:GetFrameLevel() + 2)
TukuiPetBattleHUD_EnemyPet1Health:CreateBackdrop()
TukuiPetBattleHUD_EnemyPet1HealthText = TukuiPetBattleHUD_EnemyPet1Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet1HealthText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet1HealthText:SetPoint("CENTER", TukuiPetBattleHUD_EnemyPet1Health.backdrop, "CENTER", 0, 0)
TukuiPetBattleHUD_EnemyPet1AtkPowerIcon = TukuiPetBattleHUD_EnemyPet1:CreateTexture("TukuiPetBattleHUD_EnemyPet1AtkPowerIcon", "OVERLAY")
TukuiPetBattleHUD_EnemyPet1AtkPowerIcon:SetTexture("Interface\\AddOns\\TukuiPetBattleHUD\\AtkPower")
TukuiPetBattleHUD_EnemyPet1AtkPowerIcon:Size(26)
TukuiPetBattleHUD_EnemyPet1AtkPowerIcon:SetPoint("TOPRIGHT", TukuiPetBattleHUD_EnemyPet1Health.backdrop, "LEFT", 8, 6)
TukuiPetBattleHUD_EnemyPet1AtkPowerIconText = TukuiPetBattleHUD_EnemyPet1Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet1AtkPowerIconText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet1AtkPowerIconText:SetPoint("RIGHT", TukuiPetBattleHUD_EnemyPet1Health.backdrop, "LEFT", -18, 0)
TukuiPetBattleHUD_EnemyPet1AtkSpeedIcon = TukuiPetBattleHUD_EnemyPet1:CreateTexture("TukuiPetBattleHUD_EnemyPet1AtkSpeedIcon", "OVERLAY")
TukuiPetBattleHUD_EnemyPet1AtkSpeedIcon:SetTexture("Interface\\AddOns\\TukuiPetBattleHUD\\AtkSpeed")
TukuiPetBattleHUD_EnemyPet1AtkSpeedIcon:Size(26)
TukuiPetBattleHUD_EnemyPet1AtkSpeedIcon:SetPoint("TOPRIGHT", TukuiPetBattleHUD_EnemyPet1Health.backdrop, "LEFT", 8, 4)

local TukuiPetBattleHUD_EnemyPet1Experience = CreateFrame('StatusBar', "TukuiPetBattleHUD_EnemyPet1Experience", TukuiPetBattleHUD_EnemyPet1)
TukuiPetBattleHUD_EnemyPet1Experience:SetPoint("TOP", TukuiPetBattleHUD_EnemyPet1Health, "BOTTOM", 0, -5)
TukuiPetBattleHUD_EnemyPet1Experience:Size(150, 10)
TukuiPetBattleHUD_EnemyPet1Experience:SetStatusBarTexture(normtex)
TukuiPetBattleHUD_EnemyPet1Experience:SetStatusBarColor(0.6,0,0.86)
TukuiPetBattleHUD_EnemyPet1Experience:SetFrameLevel(TukuiPetBattleHUD_EnemyPet1:GetFrameLevel() + 2)
TukuiPetBattleHUD_EnemyPet1Experience:CreateBackdrop()
TukuiPetBattleHUD_EnemyPet1ExperienceText = TukuiPetBattleHUD_EnemyPet1Experience:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet1ExperienceText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet1ExperienceText:SetPoint("CENTER", TukuiPetBattleHUD_EnemyPet1Experience.backdrop, "CENTER", 0, 0)
TukuiPetBattleHUD_EnemyPet1AtkSpeedIconText = TukuiPetBattleHUD_EnemyPet1Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet1AtkSpeedIconText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet1AtkSpeedIconText:SetPoint("RIGHT", TukuiPetBattleHUD_EnemyPet1Experience.backdrop, "LEFT", -18, 0)

local TukuiPetBattleHUD_EnemyPet2 = CreateFrame("Frame", "TukuiPetBattleHUD_EnemyPet2", TukuiPetBattleHUD_EnemyPet1)
TukuiPetBattleHUD_EnemyPet2:Size(250, 60)
TukuiPetBattleHUD_EnemyPet2:CreateBackdrop("Transparent")
TukuiPetBattleHUD_EnemyPet2:Point("TOP", TukuiPetBattleHUD_EnemyPet1, "BOTTOM", 0, -6)
TukuiPetBattleHUD_EnemyPet2NameText = TukuiPetBattleHUD_EnemyPet2:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet2NameText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet2NameText:SetPoint("TOPRIGHT", TukuiPetBattleHUD_EnemyPet2, "TOPRIGHT", -56, -5)

local TukuiPetBattleHUD_EnemyPet2IconBackdrop = CreateFrame("Frame", "TukuiPetBattleHUD_EnemyPet2IconBackdrop", TukuiPetBattleHUD_EnemyPet2)
TukuiPetBattleHUD_EnemyPet2IconBackdrop:SetPoint("RIGHT", TukuiPetBattleHUD_EnemyPet2, "RIGHT", -10, 0)
TukuiPetBattleHUD_EnemyPet2IconBackdrop:CreateBackdrop()
TukuiPetBattleHUD_EnemyPet2IconBackdrop:Size(40)
TukuiPetBattleHUD_EnemyPet2IconBackdropText = TukuiPetBattleHUD_EnemyPet2IconBackdrop:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet2IconBackdropText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet2IconBackdropText:SetPoint("BOTTOMLEFT", TukuiPetBattleHUD_EnemyPet2IconBackdrop.backdrop, "BOTTOMLEFT", 4, 2)

local TukuiPetBattleHUD_EnemyPet2IconBackdropTexture = TukuiPetBattleHUD_EnemyPet2IconBackdrop:CreateTexture("TukuiPetBattleHUD_EnemyPet2IconBackdropTexture", "OVERLAY")
TukuiPetBattleHUD_EnemyPet2IconBackdropTexture:SetTexCoord(0.08, 0.92, 0.08, 0.92)
TukuiPetBattleHUD_EnemyPet2IconBackdropTexture:SetInside(TukuiPetBattleHUD_EnemyPet2IconBackdrop.backdrop)

local TukuiPetBattleHUD_EnemyPet2Health = CreateFrame('StatusBar', "TukuiPetBattleHUD_EnemyPet2Health", TukuiPetBattleHUD_EnemyPet2)
TukuiPetBattleHUD_EnemyPet2Health:SetPoint("RIGHT", TukuiPetBattleHUD_EnemyPet2IconBackdrop.backdrop, "LEFT", -4, 0)
TukuiPetBattleHUD_EnemyPet2Health:Size(150, 10)
TukuiPetBattleHUD_EnemyPet2Health:SetStatusBarTexture(normtex)
TukuiPetBattleHUD_EnemyPet2Health:SetStatusBarColor(0.11,0.66,0.11)
TukuiPetBattleHUD_EnemyPet2Health:SetFrameLevel(TukuiPetBattleHUD_EnemyPet2:GetFrameLevel() + 2)
TukuiPetBattleHUD_EnemyPet2Health:CreateBackdrop()
TukuiPetBattleHUD_EnemyPet2HealthText = TukuiPetBattleHUD_EnemyPet2Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet2HealthText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet2HealthText:SetPoint("CENTER", TukuiPetBattleHUD_EnemyPet2Health.backdrop, "CENTER", 0, 0)
TukuiPetBattleHUD_EnemyPet2AtkPowerIcon = TukuiPetBattleHUD_EnemyPet2:CreateTexture("TukuiPetBattleHUD_EnemyPet2AtkPowerIcon", "OVERLAY")
TukuiPetBattleHUD_EnemyPet2AtkPowerIcon:SetTexture("Interface\\AddOns\\TukuiPetBattleHUD\\AtkPower")
TukuiPetBattleHUD_EnemyPet2AtkPowerIcon:Size(26)
TukuiPetBattleHUD_EnemyPet2AtkPowerIcon:SetPoint("TOPRIGHT", TukuiPetBattleHUD_EnemyPet2Health.backdrop, "LEFT", 8, 6)
TukuiPetBattleHUD_EnemyPet2AtkPowerIconText = TukuiPetBattleHUD_EnemyPet2Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet2AtkPowerIconText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet2AtkPowerIconText:SetPoint("RIGHT", TukuiPetBattleHUD_EnemyPet2Health.backdrop, "LEFT", -18, 0)
TukuiPetBattleHUD_EnemyPet2AtkSpeedIcon = TukuiPetBattleHUD_EnemyPet2:CreateTexture("TukuiPetBattleHUD_EnemyPet2AtkSpeedIcon", "OVERLAY")
TukuiPetBattleHUD_EnemyPet2AtkSpeedIcon:SetTexture("Interface\\AddOns\\TukuiPetBattleHUD\\AtkSpeed")
TukuiPetBattleHUD_EnemyPet2AtkSpeedIcon:Size(26)
TukuiPetBattleHUD_EnemyPet2AtkSpeedIcon:SetPoint("TOPRIGHT", TukuiPetBattleHUD_EnemyPet2Health.backdrop, "LEFT", 8, 4)

local TukuiPetBattleHUD_EnemyPet2Experience = CreateFrame('StatusBar', "TukuiPetBattleHUD_EnemyPet2Experience", TukuiPetBattleHUD_EnemyPet2)
TukuiPetBattleHUD_EnemyPet2Experience:SetPoint("TOP", TukuiPetBattleHUD_EnemyPet2Health, "BOTTOM", 0, -5)
TukuiPetBattleHUD_EnemyPet2Experience:Size(150, 10)
TukuiPetBattleHUD_EnemyPet2Experience:SetStatusBarTexture(normtex)
TukuiPetBattleHUD_EnemyPet2Experience:SetStatusBarColor(0.6,0,0.86)
TukuiPetBattleHUD_EnemyPet2Experience:SetFrameLevel(TukuiPetBattleHUD_EnemyPet2:GetFrameLevel() + 2)
TukuiPetBattleHUD_EnemyPet2Experience:CreateBackdrop()
TukuiPetBattleHUD_EnemyPet2ExperienceText = TukuiPetBattleHUD_EnemyPet2Experience:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet2ExperienceText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet2ExperienceText:SetPoint("CENTER", TukuiPetBattleHUD_EnemyPet2Experience.backdrop, "CENTER", 0, 0)
TukuiPetBattleHUD_EnemyPet2AtkSpeedIconText = TukuiPetBattleHUD_EnemyPet2Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet2AtkSpeedIconText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet2AtkSpeedIconText:SetPoint("RIGHT", TukuiPetBattleHUD_EnemyPet2Experience.backdrop, "LEFT", -18, 0)

local TukuiPetBattleHUD_EnemyPet3 = CreateFrame("Frame", "TukuiPetBattleHUD_EnemyPet3", TukuiPetBattleHUD_EnemyPet2)
TukuiPetBattleHUD_EnemyPet3:Size(250, 60)
TukuiPetBattleHUD_EnemyPet3:CreateBackdrop("Transparent")
TukuiPetBattleHUD_EnemyPet3:Point("TOP", TukuiPetBattleHUD_EnemyPet2, "BOTTOM", 0, -6)
TukuiPetBattleHUD_EnemyPet3NameText = TukuiPetBattleHUD_EnemyPet3:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet3NameText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet3NameText:SetPoint("TOPRIGHT", TukuiPetBattleHUD_EnemyPet3, "TOPRIGHT", -56, -5)

local TukuiPetBattleHUD_EnemyPet3IconBackdrop = CreateFrame("Frame", "TukuiPetBattleHUD_EnemyPet3IconBackdrop", TukuiPetBattleHUD_EnemyPet3)
TukuiPetBattleHUD_EnemyPet3IconBackdrop:SetPoint("RIGHT", TukuiPetBattleHUD_EnemyPet3, "RIGHT", -10, 0)
TukuiPetBattleHUD_EnemyPet3IconBackdrop:CreateBackdrop()
TukuiPetBattleHUD_EnemyPet3IconBackdrop:Size(40)
TukuiPetBattleHUD_EnemyPet3IconBackdropText = TukuiPetBattleHUD_EnemyPet3IconBackdrop:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet3IconBackdropText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet3IconBackdropText:SetPoint("BOTTOMLEFT", TukuiPetBattleHUD_EnemyPet3IconBackdrop.backdrop, "BOTTOMLEFT", 4, 2)

local TukuiPetBattleHUD_EnemyPet3IconBackdropTexture = TukuiPetBattleHUD_EnemyPet3IconBackdrop:CreateTexture("TukuiPetBattleHUD_EnemyPet3IconBackdropTexture", "OVERLAY")
TukuiPetBattleHUD_EnemyPet3IconBackdropTexture:SetTexCoord(0.08, 0.92, 0.08, 0.92)
TukuiPetBattleHUD_EnemyPet3IconBackdropTexture:SetInside(TukuiPetBattleHUD_EnemyPet3IconBackdrop.backdrop)

local TukuiPetBattleHUD_EnemyPet3Health = CreateFrame('StatusBar', "TukuiPetBattleHUD_EnemyPet3Health", TukuiPetBattleHUD_EnemyPet3)
TukuiPetBattleHUD_EnemyPet3Health:SetPoint("RIGHT", TukuiPetBattleHUD_EnemyPet3IconBackdrop.backdrop, "LEFT", -4, 0)
TukuiPetBattleHUD_EnemyPet3Health:Size(150, 10)
TukuiPetBattleHUD_EnemyPet3Health:SetStatusBarTexture(normtex)
TukuiPetBattleHUD_EnemyPet3Health:SetStatusBarColor(0.11,0.66,0.11)
TukuiPetBattleHUD_EnemyPet3Health:SetFrameLevel(TukuiPetBattleHUD_EnemyPet3:GetFrameLevel() + 2)
TukuiPetBattleHUD_EnemyPet3Health:CreateBackdrop()
TukuiPetBattleHUD_EnemyPet3HealthText = TukuiPetBattleHUD_EnemyPet3Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet3HealthText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet3HealthText:SetPoint("CENTER", TukuiPetBattleHUD_EnemyPet3Health.backdrop, "CENTER", 0, 0)
TukuiPetBattleHUD_EnemyPet3AtkPowerIcon = TukuiPetBattleHUD_EnemyPet3:CreateTexture("TukuiPetBattleHUD_EnemyPet3AtkPowerIcon", "OVERLAY")
TukuiPetBattleHUD_EnemyPet3AtkPowerIcon:SetTexture("Interface\\AddOns\\TukuiPetBattleHUD\\AtkPower")
TukuiPetBattleHUD_EnemyPet3AtkPowerIcon:Size(26)
TukuiPetBattleHUD_EnemyPet3AtkPowerIcon:SetPoint("TOPRIGHT", TukuiPetBattleHUD_EnemyPet3Health.backdrop, "LEFT", 8, 6)
TukuiPetBattleHUD_EnemyPet3AtkPowerIconText = TukuiPetBattleHUD_EnemyPet3Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet3AtkPowerIconText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet3AtkPowerIconText:SetPoint("RIGHT", TukuiPetBattleHUD_EnemyPet3Health.backdrop, "LEFT", -18, 0)
TukuiPetBattleHUD_EnemyPet3AtkSpeedIcon = TukuiPetBattleHUD_EnemyPet3:CreateTexture("TukuiPetBattleHUD_EnemyPet3AtkSpeedIcon", "OVERLAY")
TukuiPetBattleHUD_EnemyPet3AtkSpeedIcon:SetTexture("Interface\\AddOns\\TukuiPetBattleHUD\\AtkSpeed")
TukuiPetBattleHUD_EnemyPet3AtkSpeedIcon:Size(26)
TukuiPetBattleHUD_EnemyPet3AtkSpeedIcon:SetPoint("TOPRIGHT", TukuiPetBattleHUD_EnemyPet3Health.backdrop, "LEFT", 8, 4)

local TukuiPetBattleHUD_EnemyPet3Experience = CreateFrame('StatusBar', "TukuiPetBattleHUD_EnemyPet3Experience", TukuiPetBattleHUD_EnemyPet3)
TukuiPetBattleHUD_EnemyPet3Experience:SetPoint("TOP", TukuiPetBattleHUD_EnemyPet3Health, "BOTTOM", 0, -5)
TukuiPetBattleHUD_EnemyPet3Experience:Size(150, 10)
TukuiPetBattleHUD_EnemyPet3Experience:SetStatusBarTexture(normtex)
TukuiPetBattleHUD_EnemyPet3Experience:SetStatusBarColor(0.6,0,0.86)
TukuiPetBattleHUD_EnemyPet3Experience:SetFrameLevel(TukuiPetBattleHUD_EnemyPet3:GetFrameLevel() + 2)
TukuiPetBattleHUD_EnemyPet3Experience:CreateBackdrop()
TukuiPetBattleHUD_EnemyPet3ExperienceText = TukuiPetBattleHUD_EnemyPet3Experience:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet3ExperienceText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet3ExperienceText:SetPoint("CENTER", TukuiPetBattleHUD_EnemyPet3Experience.backdrop, "CENTER", 0, 0)
TukuiPetBattleHUD_EnemyPet3AtkSpeedIconText = TukuiPetBattleHUD_EnemyPet3Health:CreateFontString(nil, "OVERLAY")
TukuiPetBattleHUD_EnemyPet3AtkSpeedIconText:SetFont(font, fontsize, fontflag)
TukuiPetBattleHUD_EnemyPet3AtkSpeedIconText:SetPoint("RIGHT", TukuiPetBattleHUD_EnemyPet3Experience.backdrop, "LEFT", -18, 0)
--
TukuiPetBattleHUD = CreateFrame("Frame")
TukuiPetBattleHUD:RegisterEvent("PLAYER_ENTERING_WORLD")
TukuiPetBattleHUD:SetScript("OnEvent", function(self, event)
	self:SetScript("OnUpdate", function()
		for i = 1, 3 do
			local petID = C_PetJournal.GetPetLoadOutInfo(i)
			if petID == nil then return end
			local _, customName, level, xp, maxXp, _, _, name, icon, petType = C_PetJournal.GetPetInfoByPetID(C_PetJournal.GetPetLoadOutInfo(i))
			local hp, maxhp, power, speed, rarity = C_PetJournal.GetPetStats(C_PetJournal.GetPetLoadOutInfo(i))
			local r, g, b = GetItemQualityColor(rarity-1)
			_G["TukuiPetBattleHUD_Pet"..i.."IconBackdrop"].backdrop:SetBackdropBorderColor(r,g,b)
			_G["TukuiPetBattleHUD_Pet"..i.."IconBackdropTexture"]:SetTexture(icon)
			_G["TukuiPetBattleHUD_Pet"..i.."IconBackdropText"]:SetText(level)
			if C_PetBattles.IsInBattle() then
				allyxp, allymaxXP = C_PetBattles.GetXP(LE_BATTLE_PET_ALLY, i)
				enemyxp, enemymaxXP = C_PetBattles.GetXP(LE_BATTLE_PET_ENEMY, i)
				enemylevel = C_PetBattles.GetLevel(LE_BATTLE_PET_ENEMY, i)
				enemyicon = C_PetBattles.GetIcon(LE_BATTLE_PET_ENEMY, i)
				enemyquality = C_PetBattles.GetBreedQuality(LE_BATTLE_PET_ENEMY, i)
				local er, eg, eb = GetItemQualityColor(enemyquality-1)
				local enemyframes = C_PetBattles.GetNumPets(LE_BATTLE_PET_ENEMY)
				if enemyframes == 1 then
					TukuiPetBattleHUD_EnemyPet1:Show()
				elseif enemyframes == 2 then
					TukuiPetBattleHUD_EnemyPet1:Show()
					TukuiPetBattleHUD_EnemyPet2:Show()
				elseif enemyframes == 3 then
					TukuiPetBattleHUD_EnemyPet1:Show()
					TukuiPetBattleHUD_EnemyPet2:Show()
					TukuiPetBattleHUD_EnemyPet3:Show()
				end
				_G["TukuiPetBattleHUD_Pet"..i.."NameText"]:SetText(C_PetBattles.GetName(LE_BATTLE_PET_ALLY, i))
				_G["TukuiPetBattleHUD_Pet"..i.."NameText"]:SetTextColor(r, g, b)
				_G["TukuiPetBattleHUD_Pet"..i.."Health"]:SetMinMaxValues(0, C_PetBattles.GetMaxHealth(LE_BATTLE_PET_ALLY, i))
				_G["TukuiPetBattleHUD_Pet"..i.."Health"]:SetValue(C_PetBattles.GetHealth(LE_BATTLE_PET_ALLY, i))
				_G["TukuiPetBattleHUD_Pet"..i.."HealthText"]:SetText(C_PetBattles.GetHealth(LE_BATTLE_PET_ALLY, i).." / "..C_PetBattles.GetMaxHealth(LE_BATTLE_PET_ALLY, i))
				_G["TukuiPetBattleHUD_Pet"..i.."Experience"]:SetMinMaxValues(0, allymaxXP)
				_G["TukuiPetBattleHUD_Pet"..i.."Experience"]:SetValue(allyxp)
				_G["TukuiPetBattleHUD_Pet"..i.."ExperienceText"]:SetText(allyxp.." / "..allymaxXP)
				_G["TukuiPetBattleHUD_Pet"..i.."AtkPowerIconText"]:SetText(C_PetBattles.GetPower(LE_BATTLE_PET_ALLY, i))
				_G["TukuiPetBattleHUD_Pet"..i.."AtkSpeedIconText"]:SetText(C_PetBattles.GetSpeed(LE_BATTLE_PET_ALLY, i))

				_G["TukuiPetBattleHUD_EnemyPet"..i.."NameText"]:SetText(C_PetBattles.GetName(LE_BATTLE_PET_ENEMY, i))
				_G["TukuiPetBattleHUD_EnemyPet"..i.."NameText"]:SetTextColor(er, eg, eb)
				_G["TukuiPetBattleHUD_EnemyPet"..i.."Health"]:SetMinMaxValues(0, C_PetBattles.GetMaxHealth(LE_BATTLE_PET_ENEMY, i))
				_G["TukuiPetBattleHUD_EnemyPet"..i.."Health"]:SetValue(C_PetBattles.GetHealth(LE_BATTLE_PET_ENEMY, i))
				_G["TukuiPetBattleHUD_EnemyPet"..i.."HealthText"]:SetText(C_PetBattles.GetHealth(LE_BATTLE_PET_ENEMY, i).." / "..C_PetBattles.GetMaxHealth(LE_BATTLE_PET_ENEMY, i))
				_G["TukuiPetBattleHUD_EnemyPet"..i.."Experience"]:SetMinMaxValues(0, enemymaxXP)
				_G["TukuiPetBattleHUD_EnemyPet"..i.."Experience"]:SetValue(enemyxp)
				_G["TukuiPetBattleHUD_EnemyPet"..i.."ExperienceText"]:SetText(enemyxp.." / "..enemymaxXP)
				_G["TukuiPetBattleHUD_EnemyPet"..i.."AtkPowerIconText"]:SetText(C_PetBattles.GetPower(LE_BATTLE_PET_ENEMY, i))
				_G["TukuiPetBattleHUD_EnemyPet"..i.."AtkSpeedIconText"]:SetText(C_PetBattles.GetSpeed(LE_BATTLE_PET_ENEMY, i))
				_G["TukuiPetBattleHUD_EnemyPet"..i.."IconBackdrop"].backdrop:SetBackdropBorderColor(er, eg, eb)
				_G["TukuiPetBattleHUD_EnemyPet"..i.."IconBackdropTexture"]:SetTexture(enemyicon)
				_G["TukuiPetBattleHUD_EnemyPet"..i.."IconBackdropText"]:SetText(enemylevel)
			else
				TukuiPetBattleHUD_EnemyPet1:Hide()
				TukuiPetBattleHUD_EnemyPet2:Hide()
				TukuiPetBattleHUD_EnemyPet3:Hide()
				if customName then
					_G["TukuiPetBattleHUD_Pet"..i.."NameText"]:SetText(customName)
				else
					_G["TukuiPetBattleHUD_Pet"..i.."NameText"]:SetText(name)
				end
				_G["TukuiPetBattleHUD_Pet"..i.."AtkPowerIconText"]:SetText(power)
				_G["TukuiPetBattleHUD_Pet"..i.."AtkSpeedIconText"]:SetText(speed)
				_G["TukuiPetBattleHUD_Pet"..i.."NameText"]:SetTextColor(r, g, b)
				_G["TukuiPetBattleHUD_Pet"..i.."Experience"]:SetMinMaxValues(0, maxXp)
				_G["TukuiPetBattleHUD_Pet"..i.."Experience"]:SetValue(xp)
				_G["TukuiPetBattleHUD_Pet"..i.."ExperienceText"]:SetText(xp.." / "..maxXp)
				_G["TukuiPetBattleHUD_Pet"..i.."Health"]:SetMinMaxValues(0, maxhp)
				_G["TukuiPetBattleHUD_Pet"..i.."Health"]:SetValue(hp)
				_G["TukuiPetBattleHUD_Pet"..i.."HealthText"]:SetText(hp.." / "..maxhp)
			end
		end
	end)
end)
local function GetPetDumpList(targetID)
	local returned = nil

	for i=1,C_PetJournal.GetNumPets(false) do 
		id,speciesID,_,_,_,_,_,n,_,_,_,d=C_PetJournal.GetPetInfoByIndex(i)
		
		if speciesID == targetID then
			if returned == nil then
				returned = C_PetJournal.GetBattlePetLink(id)
			else
				returned = returned..", "..C_PetJournal.GetBattlePetLink(id)
			end
		end
	end
	
	return returned
end
local function PetDump()
	local isWildPetBattle = (C_PetBattles.IsInBattle() and C_PetBattles.IsWildBattle())

	if (isWildPetBattle) then 
		local activePet = C_PetBattles.GetActivePet(LE_BATTLE_PET_ENEMY)
		local targetID = C_PetBattles.GetPetSpeciesID(LE_BATTLE_PET_ENEMY, activePet)
		
		PetBattlePetDumpActive = GetPetDumpList(targetID)
		if PetBattlePetDumpCompare == nil then PetBattlePetDumpCompare = GetPetDumpList(targetID) end
		if PetBattlePetDumpActive ~= PetBattlePetDumpCompare then PetBattlePetDumpActive = GetPetDumpList(targetID) PetBattlePetDumpCompare = GetPetDumpList(targetID) PetBattlePetDumpedOnce = nil end
			if PetBattlePetDumpedOnce == nil then
				if PetBattlePetDumpActive == nil then
					RaidNotice_AddMessage(RaidWarningFrame, "You do not own this pet.", ChatTypeInfo["RAID_WARNING"])
					PetBattlePetDumpedOnce = true
				else
					RaidNotice_AddMessage(RaidWarningFrame, "Owned: "..PetBattlePetDumpActive, ChatTypeInfo["RAID_WARNING"])
					PetBattlePetDumpedOnce = true
				end
			end
	end
end
local PetBattlePetDump = CreateFrame("Frame")
PetBattlePetDump:RegisterEvent("PET_BATTLE_PET_CHANGED")
PetBattlePetDump:RegisterEvent("PET_BATTLE_CLOSE")
PetBattlePetDump:SetScript("OnEvent", function(self,event)
	if event == "PET_BATTLE_PET_CHANGED" then
		PetDump()
	elseif event == "PET_BATTLE_CLOSE" then
		PetBattlePetDumpedOnce = nil
		PetBattlePetDumpCompare = nil
	end
end)
hooksecurefunc("PetBattleFrame_Display", PetDump)